name: Build App

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Select Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Build project
        run: ./.github/scripts/build_app.sh
      - name: Exporting .zip
        run: ./.github/scripts/export_zip.sh
      - name: Save .zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: keyrace.zip
          path: ./build/keyrace.zip
